### ISSUE TITLE
Bug max.substring

### ISSUE THREAD

**Issue by fabiancarlos** [netconvdelivery/react-native-schedule-hours#3]
Talvez, seria uma boa fazer o seguinte:

1. Um repositório com exemplos do código sendo utilizado em um projeto real.
2. Prints da tela da lib rodando em um projeto teste. 

<img width="323" alt="Screen Shot 2020-08-06 at 10 46 41 PM" src="https://user-images.githubusercontent.com/636804/89603369-fba5c480-d836-11ea-9bc1-e131d4e00c6c.png">

**Comment by mdlucas** [comment]
Resolvido na versão 1.0.10
